import Head from 'next/head'
import ProductCard from '../src/components/ProductCard/ProductCard'

const data = {
  title: "Brown eggs",
  type: "dairy",
  description: "Raw organic brown eggs in a basket",
  filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/0.jpg",
  height: 600,
  width: 400,
  price: 28.1,
  rating: 4,
  id: "p-0",
};


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div><ProductCard data={data}/></div>
      </main>
    </div>
  )
}
